version: "2"

volumes:
#  data_mysql:
#    driver: local
  data_redis:
    driver: local

services:

  code:
    image: tianon/true
    volumes:
      - ./:/app

#  Container for service
  workspace:
    build:
      context: docker/php
      args:
        - INSTALL_COMPOSER=true
        - INSTALL_PHPUNIT=true
    volumes_from:
      - code
    links:
      - web
      - db
    tty: true
    env_file:
      - .env.docker
    working_dir: /app
    command: sh -c "sh"

#  PHP-FPM
  php:
    build:
      context: docker/php
    volumes_from:
      - code
    links:
      - db
    tty: true
    env_file:
      - .env.docker

# nginx
  web:
    build:
      context: docker/nginx
    volumes_from:
      - code
    ports:
      - 8085:80
    links:
      - php
    environment:
     - NGINX_HOST=chat.loc
     - NGINX_PORT=80
     - FPM_HOST=php
     - FPM_PORT=9000

  db:
    image: mariadb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: secret
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
